### ISSUE TITLE
Did not work for GeoIP2

### ISSUE THREAD

**Issue by shenzhun** [mteodoro/mmutils#8]
Hi there,

I tried to use this project to convert GeoIP2 csv to dat file. But it did not work. Do you have plan to add this feature ?

**Comment by mteodoro** [comment]
These tools work with the MaxMind Legacy format.  The GeoIP2 files are meant to work with the new database format: http://maxmind.github.io/MaxMind-DB/.  MaxMind provides a writer for the new format: https://github.com/maxmind/MaxMind-DB-Writer-perl.

**Comment by mteodoro** [comment]
Updated docs to point at GeoIP2 info: 5872a1fc26985b457c4cc1d3f2e4a035a7d3954a
